### ISSUE TITLE
install fails on a system without wget

### ISSUE THREAD

**Issue by mtmiller** [gnu-octave/pkg-json#1]
Can you replace wget with curl, which is more common these days? Or maybe consider vendoring the RapidJSON source in the tar so no download is needed at install time?

**Comment by mtmiller** [comment]
Ideally you could add RapidJSON as a git submodule, but you would then have to build and upload your own release tarballs using git-archive-all or other custom commands.

**Comment by siko1056** [comment]
Thanks for the suggestion.  I pushed a change to use cURL instead.  Tomorrow I can do testing on macOS and MS Windows, than follows a new release.  You can use the development version already.

For now I prefer the current "loose" downloading coupling to rapid-json, for the reasons mentioned by your already :slightly_smiling_face:

**Comment by mtmiller** [comment]
Installing from main works for me now, thanks!
